data:
  root_file: data/Agata/GammaEvents_0000_train_dedx.root
  max_layer: 5
  
analysis:
  features: ['b_in', 'b_out', 'dE_1', 'dE_2', 'dE_3', 'dE_4', 'dE_5']
  target: reaction_layer
  models: ['logreg', 'rf', 'knn', 'gb','mlp']
  #models: ['logreg', 'rf', 'knn', 'gb']
  #models: ['logreg', 'rf', 'knn']
  test_size: 0.2
  layer_min: 1
  layer_max: 5
